### ISSUE TITLE
Not able to connect to Mongodb by using morphium

### ISSUE THREAD

**Issue by narendrar-egnaroinc** [sboesebeck/morphium#10]
I'm using Ubunut 14.04, Java 8, Mongodb 2.6.11. morphium-2.2.22.jar, mongo-java-driver2.11.3.jar

I'm just doing sample program how to connect with mongodb by using Morphium. I posted my code below

class 1: test.java 
        private ObjectId myId;
        private String aField;
        private String name;
        //Getters & Setters
class 2:

MorphiumConfig cfg = new MorphiumConfig();
      cfg.setDatabase("testdb");
      try{
      cfg.addHost("localhost", 27017);
      }catch(UnKnownHostExcepection  e){
          e.printStackTrace();
      }

      Morphium morphium=new Morphium(cfg);

     test testObj  = new test();
     testObj.setaField("test");
     testObj.setName("first");
     morphium.store(testObj)
.............

I tried to debug, I've seen an exception com.sun.jdi.InvocationException occurred invoking method, when I mouse over on MorphiumConfig cfg = new MorphiumConfig();, shown in below image.
![screenshot from 2015-09-02 16 01 18](https://cloud.githubusercontent.com/assets/10140555/9636871/761c165e-51bb-11e5-915e-75f28d645ee1.png)

so I keep on go for next step, when controller come to Morphium morphium=new Morphium(cfg); line its existing from the program and attached an image can see below. 

![screenshot from 2015-09-02 16 01 40](https://cloud.githubusercontent.com/assets/10140555/9636930/a79c09b4-51bb-11e5-9295-4be02dbf7c34.png)

I googled but could not found any help.

Can some one please help me in bellow points.?

1) Am I using correct version drivers(I've used morphium2.0.22.jar)? and Is my program correct?
2) Could you please show an example which will work for me?

Thanks in advance.

**Comment by sboesebeck** [comment]
Hi,

the versions are correct...

Your code should work, cannot reproduce this issue here. Could you give more info on that?
