### ISSUE TITLE
Support Codec API introduces in MongoDB driver v3

### ISSUE THREAD

**Issue by ainlolcat** [sboesebeck/morphium#11]
I'd like to use BigInteger in my POJO but cannot use it because BSON does not supports BigInteger OOB yet. But in MongoDB driver v3 was introduced new API for Codecs http://mongodb.github.io/mongo-java-driver/3.0/driver/reference/crud/ and now anyone can write codec to decode/encode any data. I dont really need exactly Codec API. Any wrapper like org.mongodb.morphia.converters.TypeConverter will be fine.

**Comment by sboesebeck** [comment]
Hi,

as BigIntegers are serializable, Morphium is also able to store it as a binary serialized object. Morphium does not support those codecs yet. The reason is, that the 3.0 driver is almost totally different, the api did change quite substancially. It has support for the "old" 2.x-Api, but this is deprecated and lacks some features (like codecs and such).

**Comment by ainlolcat** [comment]
Thank You.
Yep I seen this part but I cannot serialize Entity which has BigInteger Id.
```
public class AbstractEntity
{
    @Id
    private BigInteger ID;

    public AbstractEntity() {}

    public AbstractEntity(BigInteger ID) {
        this.ID = ID;
    }

    public BigInteger getID() {
        return ID;
    }

    public void setID(BigInteger id) {
        this.ID = id;
    }

}

@Entity
public class MyEntityImpl extends AbstractEntity{}
```

**Comment by sboesebeck** [comment]
sorry, I was wrong. BigInteger is not serializable unfortunately.

But (just brainstorming here): you could serialize and deserialize it yourself using byte array or string (better). If you stored your BigInteger as a hex string representation, this would work.

you could actually use the @lifecycle Methogs @preStore and @postLoad to do that automatically...

**Comment by ainlolcat** [comment]
Strange. BigInteger must be serializable because it extends Number which is marked as serializable.

**Comment by sboesebeck** [comment]
hmm... hard to decide... Maybe I could build something into morphium, that would not be too hard, actually... I'll investigate.

But It wont be part of the current 2.2.23, maybe next release...

**Comment by ainlolcat** [comment]
I will try Morphia for awhile. I hope I can try it in next release because Morpheus feature list is awesome. Thank You.

**Comment by sboesebeck** [comment]
hmm... we were thinking about adding this "Codec"-Feature ourselves. This is not hard to implement, and would substencially increase the use of morphium.

Probably in the next release...

**Comment by sboesebeck** [comment]
part of Morphium 2.2.23
