### ISSUE TITLE
Java Async Driver

### ISSUE THREAD

**Issue by mancvso** [sboesebeck/morphium#18]
Can this be used with the java async driver?

**Comment by sboesebeck** [comment]
no, it cannot. Morphium is in itself asynchrounous and uses the same mechanisms the async driver from mongodb uses.

Any call to morphium can be done asynchronously...

**Comment by mancvso** [comment]
Got it. Thanks. A little more marketing on that side could help.

**Comment by sboesebeck** [comment]
ok, good idea... will add that to the feature list... thanks for pointing that out.
