### ISSUE TITLE
Threads should be named as per their purpose for easy monitoring

### ISSUE THREAD

**Issue by TheNilesh** [sboesebeck/morphium#33]
When we **shutdown** the web app, various exception stack traces are printed on console. We suspect some of them are caused by **morphium**.
```

WARNING: The web application [myserver] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 de.caluga.morphium.cache.CacheHousekeeper.run(CacheHousekeeper.java:274)
```

It would be great if we could name threads as per their purpose (eg, morphium-cache-housekeeper).

**Comment by sboesebeck** [comment]
There are not so many threads in morphium, most of asynchronous functionalities use executors and threadpools. But for the ones I found, I set a proper name.

you can see changes in dev branch.
