### ISSUE TITLE
Generated ID while storing list

### ISSUE THREAD

**Issue by szmark** [sboesebeck/morphium#36]
Upon storing single value with `@Id` annotated `String` type value will generate ObjectId as expected, but if I wrap the values into list and calling `Morphium.storeList` wont produces the same behavior.
See: `de.caluga.morphium.writer.MorphiumWriterImpl:494`

**Comment by sboesebeck** [comment]
fixed on develop... will be added to next release...

**Comment by sboesebeck** [comment]
fixed in 3.1.2
