### ISSUE TITLE
Requests to Mongo database are duplicated when the method "Driver.find" is used.

### ISSUE THREAD

**Issue by TomWolk** [sboesebeck/morphium#38]
In the class src/de/caluga/morphium/driver/mongodb/Driver.java a request will be sent to the Mongo database when DBCursor.hasNext() ist called on line 673. On line 691 an Iterator is created for the for each loop. But calling the method iterator() on DBCursor does return a clone which does not know of ther first request and when the for each loop calls hasNext() a new request will be sent to the Mongo database. DBCursor is a little sensitive to this kind of usage mistake because it implements both of the interfaces Iterator and Iterable and the method iterator() returns a clone and not itselfe.

Additionally neither of the cursors is closed.

**Comment by sboesebeck** [comment]
Thanks for pointing that out. Will be fixed in next release...

**Comment by sboesebeck** [comment]
already added a fix to develop.
