### ISSUE TITLE
Using ObjectId instead of MorphiumId

### ISSUE THREAD

**Issue by SoberTomYorke** [sboesebeck/morphium#48]
I am upgrading Morphium's version in my project to 4.0.7 from 2.23. Earlier, we were using ObjectId for id's and now it is showing an error: 

ERROR de.caluga.morphium.ObjectMapperImpl - ID type missmatch
at de.caluga.morphium.ObjectMapperImpl.deserialize(ObjectMapperImpl.java:1016)
	at de.caluga.morphium.query.QueryImpl.get(QueryImpl.java:904)
Caused by: java.lang.IllegalArgumentException: ID type missmatch. Field in 'class Entity.Abc' is 'class org.bson.types.ObjectId' but we got 'class de.caluga.morphium.driver.MorphiumId' from Mongo!
at de.caluga.morphium.ObjectMapperImpl.deserialize(ObjectMapperImpl.java:1003)

I'll have to change lots of code to change from ObjectId to MorphiumId

I have found a workaround though. I'll create a new custom ObjectMapper which will extend ObjectMapperImpl. I'll set this as OmClass in config. 
This custom ObjectMapper will only provide provision for ObjectId by adding one more else if statement around line 995(of ObjectMapperImpl) in tag 4.0.7.0.

I wanted to ask, was there any specific reason you didn't allow the use of ObjectId? Also, if I do the patch as I mentioned earlier, will it impact anything?

**Comment by sboesebeck** [comment]
Morphium was built to be very flexible, so a custom ObjectMapper is actually the way to go, if you have special needs. The impact should be minimal, as Morphium was built for that. The Mapper takes any object ans maps that to a HashMap. 

What also might work with less effort is to register a custom mapper for your entitiy and deal with it there... might also be a solution, maybe one that is easier.
`morphium.getMapper().registerCustomMapperFor(theClass,mapperInstance);`

Or you use Pre-Store and such lifecycle methods to do a custom migration... might work..

the reason for the introduction of MorphiumID was problems we had with the mongodb driver and especially with the changes in Object Mappings at that time. 
Morphium does not have a direct dependency to a sepcific mongodb driver (only "provided"), so you could use morphium with  the latest drivers, even if it was tested against an earlier version. So we wanted to make it as independent from mongodb as possible. so we introduces MorphiumId... This also made it possible to have custom drivers in Morphium, e.g. Drivers accessing other databases (influxDB) or an simpler Implementation of the WiredProtocol mongodb uses.

Sorry, that it causes so much trouble in your case, but MorphiumID should be method compatible to ObjectID, so a ReplaceAll should work. Unfortunately the Writers in Morphium _assumes_ that no ObjectID is used outside of Morphium and translates them on over the other.

**Comment by SoberTomYorke** [comment]
I tried registering my custom mapper for ObjectId deserialization. The problem with that is, while fetching an object from DB, it will deserialize using deserialize method of ObjectMapperImpl, at line 573. It will encounter the loop starting at 629. For the case of field id(annotated with `@Id`), the value of `valueFromDB = o.get(f)` will be null as it gets _id from DB and the name of my field is id. Now, there will be a check on line 637, if there is a custom mapper present for the type ObjectId, and there is. So, it will try to deserialize "null" to ObjectId using my custom Mapper's method. This will lead to an NPE.
If I don't register my custom mapper for ObjectId, this id field will be null after the execution of this loop, and will be populated later in the "if" condition starting at Line 984. This would work fine.
So, I don't think I can use a custom mapper only for ObjectId. 
Please point out if I have misunderstood this.

**Comment by sboesebeck** [comment]
I was thinking about a custom mapper for your Entity not for ObjectId. There you could handle the _id. But ObjectId _and_ _id is handled special in Morphium unfortunately. 

As mentioned, the custom Mapper is also fine. But feels a bit "big" considered the small issue.

Or: replace all ObjectIds in your code with MorphiumIDs - is that a big issue?

**Comment by sboesebeck** [comment]
join the slack-channel, maybe I could help there more.

**Comment by SoberTomYorke** [comment]
The link to join slack seems to have been expired(https://team-morphium.slack.com/join/shared_invite/enQtMjgwODMzMzEzMTU5LTA1MjdmZmM5YTM3NjRmZTE2ZGE4NDllYTA0NTUzYjU2MzkxZTJhODlmZGQ2MThjMGY0NmRkMWE1NDE2YmQxYjI, as mentioned in the documentation). Is there an alternate link?

**Comment by GermanGeekN** [comment]
Try this one here please. https://join.slack.com/t/team-morphium/shared_invite/enQtMjgwODMzMzEzMTU5LWU3MWI3ZjA3YWNiNWM0ZDU2NDQyZjBkOTY5MmFiODExZjg2ZDAxODAzMmM2MmM1ZmVkYzExNzBhOTZjNzY1OWQ

**Comment by SoberTomYorke** [comment]
Thanks a lot for your help guys. Closing this issue hoping ObjectId will be supported in later releases. Going with Custom OM class for now.
