### ISSUE TITLE
Make Morphium Compatible to DocumentDB

### ISSUE THREAD

**Issue by manzinger** [sboesebeck/morphium#53]
Hi Stephan,

we are upgrading HI-Mongo to AWS DocumentDB. There are some Problems with FSync in Driver.java

FSync must be null instead of false when using Amazon DocumentDB. There is an error if fsync=false and j=false

then the Morphium Driver is compatible to Amazon DocumentDB

**Comment by sboesebeck** [comment]
ok... Thanks for pointing that out, we will include that in the upcoming release!
I'll post here, if it's in dev.

**Comment by manzinger** [comment]
in our Patched Version I added this method to de.caluga.morphium.driver.WriteConcern:

```
public com.mongodb.WriteConcern toMongoWriteConcern() {
        com.mongodb.WriteConcern wc = getW() > 0 ? com.mongodb.WriteConcern.ACKNOWLEDGED : com.mongodb.WriteConcern.UNACKNOWLEDGED;
        if (getW() > 0) {
            if (isJ()) {
                wc = wc.withJournal(isJ());
            } else if (isFsync()) {
                // do not set if journal is already set - otherwise AWS DocumentDB will throw an error. fsync must be null not only false
                wc = wc.withFsync(isFsync());
            }
            if (getWtimeout() > 0) {
                wc.withWTimeout(getWtimeout(), TimeUnit.MILLISECONDS);
            }
        }
        return wc;
    }
```

**Comment by manzinger** [comment]
in Driver.java i replaced the writeConcern in the connect method with:
`o.writeConcern(WriteConcern.getWc(getDefaultW(), isDefaultFsync(), isDefaultJ(), getWriteTimeout()).toMongoWriteConcern());`

and all others with wc.toMongoWriteConcern() instead of building new Objects

**Comment by sboesebeck** [comment]
could you create a pull request for it?

**Comment by sboesebeck** [comment]
included in develop branch, tests are green....
