### ISSUE TITLE
Log output clutter

### ISSUE THREAD

**Issue by ribomation** [sboesebeck/morphium#6]
I see this annoying log print-out for every @Entity annotated class.

    WARN MorphiumWriterImpl:604 - cannot cap collection for class com.whatever.Xyz not @Capped
Would appreciate if line 604 were commented out
```
if (capped != null) {. . .} else {
    logger.warn("cannot cap collection for class " + c.getName() + " not @Capped");
    return;
}
```

**Comment by sboesebeck** [comment]
Yes, you are right. This is not really useful. Next release will address it. Thanks

**Comment by sboesebeck** [comment]
it is already in V2.21BETA, will be out in a couple of days probably
