### ISSUE TITLE
Obviously Mongodb supports now subdocuments with non-string keys

### ISSUE THREAD

**Issue by sboesebeck** [sboesebeck/morphium#60]
morphium does not support that. With the latest pull request from @TomWolk the support for reading those maps was added to the objectmapper. Unfortunately, serlializing of those maps is not supported.

Todo:

- in order to keep it backward compatible, we should keep the API as it is, top Level still is a`Map<String,Object>`
- when serializing, we need to detect whether we are serializing top level and maybe divert into serializing to `Map<Object,Object>`
- this might be tricky dealing with the recursion in Object serialization

**Comment by GermanGeekN** [comment]
yes it does. but it also allows it on top-level. We need to change the API for that to work....

**Comment by sboesebeck** [comment]
yes, but with java this does not make a lot of sense, does it? How would an `Entity` using that look like?

The only way, this is possible would be using `@Additional` and have it stored there. But this should be working out of the box, right?

**Comment by GermanGeekN** [comment]
I will check...

**Comment by GermanGeekN** [comment]
The MongoDBDriver does not allow top level keys with Non-Strings. 

```
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:208)
```

so... I guess, we will have to go with the first idea in a more complex way: the Top-Level-Map needs to be String,Object, all sup-Documents may be Object,Object. This is tough...

**Comment by GermanGeekN** [comment]
Correction: with this Version of the MongoDBDriver that cannot be fixed! The driver does not support keys that are non-strings at the moment. Unfortunately we need probably upgrade to the 4.0-Drivers which have a different API.
