### ISSUE TITLE
Aggregator does not sort

### ISSUE THREAD

**Issue by GermanGeekN** [sboesebeck/morphium#64]
When aggregating, adding a "$sort" to the pipeline needs to be done exatly at that place. For some reason, it will always be done before the "$group". So you cannot sort your results properly.

Todo: keep the order of the pipeline as requested.

**Comment by sboesebeck** [comment]
I cannot reproduce the error - did you call `end()` on the group in order to have it added to the pipeline correctly? If not, it will be added at the end of the pipeline by default...

**Comment by GermanGeekN** [comment]
sorry, my bad... you're right. I forgot to call `end()` on group... no bug here. 

Thanks.
