### ISSUE TITLE
Question on Mongo Aggregator - way to support this type of query?

### ISSUE THREAD

**Issue by pkalwar** [sboesebeck/morphium#81]
Hi,
Thank you for this great project. 
I've a question: How to code in morphium below type of query?

<pre>
db.collection1.aggregate([
        {
            "$match": {                                    // any type of query
              "amount": {
                "$lte": 10
              }
            }
          },
	  {
	    "$group": {
	      "_id": "$branch",				// or group by multiple::  "_id": {"field1": "$field1", "f2":"$f2", ...}
	      "doc": {
	        $push: "$$ROOT"				// push whole object. 
	      }
	    }
	  },
	  {
	    "$project": {
	      "_id": {
	        "$arrayElemAt": [
	          "$doc",
	          {
	            "$indexOfArray": [
	              "$doc.amount",
	              {
	                "$max": "$doc.amount"
	              }
	            ]
	          }
	        ]
	      }
	    }
	  }
	])
</pre>

it gives the whole object (ie all fields) from collection1, group by branch field, where amount is max (per branch), with a filter query first.. Assuming i've an index on branch and amount fields

I did look at  https://github.com/sboesebeck/morphium/wiki/Aggregator-Framework-Support  but not sure if this gives like above.

Or any other way to get above desired results in a better-way/efficiently?

Thank you.

**Comment by sboesebeck** [comment]
hmm... It should work. Morphium Aggregator just takes your pipeline and translates the results into your destination class. 

it would look something like this:

```java
        Aggregator<UncachedObject, Aggregate> a = morphium.createAggregator(collection_one.class, Aggregate.class);
        a = a.match(morphium.createQueryFor(collection_one.class).f(UncachedObject.Fields.counter).lte(10));
        a = a.group("branch").push("doc", "$$ROOT").end();

        HashMap<String, Object> projection = new HashMap<>();
        projection.put("_id", UtilsMap.getMap("$arrayElementAt", your list from above);
        a = a.project(projection);
        List<Aggregate> lst = a.aggregate();
```

not 100% sure about this, but this is kind of how it should work.

There is a testcase, that might help a bit, maybe. (`Aggregation.java` in `de.caluga.test.mongo.suite.base`).

let me know, if it worked, love to read about it.

**Comment by pkalwar** [comment]
thank you. I'll try and let you know.
