### ISSUE TITLE
de.caluga.morphium.ObjectMapperImpl.deserialize is giving class not found exception on localhost

### ISSUE THREAD

**Issue by rahulb3166** [sboesebeck/morphium#84]
@Entity(collectionName = "docs")
public class Docs{
Tmp tmp;
}

@Embedded
public class Tmp{
}

I am getting de.caluga.morphium.ObjectMapperImpl.deserialize is giving class not found exception on localhost for collection named docs which is "Embedding collection Tmp".

I am using Morphium version 4.0.7.1

**Comment by sboesebeck** [comment]
Can you tty that with a newer version of morphium, prefrably 5.1.6?

But i‘ll try to have a look at the old code

**Comment by rahulb3166** [comment]
Hi Stephan, thank you for the reply. I tried using 4.2.13, but ran into an authentication issue. Turns out whatever database I set in MorphiumConfig before instantiating the Morphium object, that database is being treated as the auth source as well. Is there any way to specify the database to use, and the auth source separately?
Thanks in advance.

**Comment by rahulb3166** [comment]
UPDATE :

 The authentication issue has been resolved and the morphium is also upgraded but the original URL class Loader issue persist.

Is there a way to resolve this?

java.lang.IllegalArgumentException: Could not find class
	at de.caluga.morphium.ObjectMapperImpl.fillCollection(ObjectMapperImpl.java:1313)
	at de.caluga.morphium.ObjectMapperImpl.fillCollection(ObjectMapperImpl.java:1389)
	at de.caluga.morphium.ObjectMapperImpl.deserialize(ObjectMapperImpl.java:1038)
	... 41 common frames omitted
Caused by: java.lang.ClassNotFoundException: models. Tmp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at de.caluga.morphium.AnnotationAndReflectionHelper.getClassForTypeId(AnnotationAndReflectionHelper.java:129)
	at de.caluga.morphium.ObjectMapperImpl.fillCollection(ObjectMapperImpl.java:1307)

**Comment by sboesebeck** [comment]
Is the package name `model`? If so, this seems like morphium is using a different classloader and hence a different classpath. I remember having this kind if issues with some webcontainers. I had to offer morphium via the container (e.g. put it in the lib directory of tomcat). The code seems fine and the errormessage hints in that direction

**Comment by rahulb3166** [comment]
Thanks for the reply. As a workaround, is there a way so that the field "class_name" doesn't get set in the Wheel object. I'm thinking of override setters and using a custom objectMapper to convert the list of objects(or strings) to populate the list of wheels in Car.

**Comment by sboesebeck** [comment]
You can create and register  a customMapper for that case. Then you have mor control over serialisation and deserialisation. 

Usually, the class_name is only set, if morphium cannot determin the type by itself. And with lists that is often the case.

**Comment by rahulb3166** [comment]
Thanks a lot for the reply. I was just curious if there was a way to resolve the Custom Class Loader issue?
